### ISSUE TITLE
博主下载了官方的工具,修改样式后将css文件导入吗?

### ISSUE THREAD

**Issue by LYL98** [oyai32/vuebase#1]

**Comment by oyai32** [comment]
官方工具？我是参照element自定义主题的方式，执行et -i命令，拿到element的scss文件，然后进行修改的，有些改不了的地方就重写了

**Comment by LYL98** [comment]
哦哦,如果要生成动态路由,就是根据后台传回来的角色不同,显示不同侧边栏,应该在哪里设置呢

**Comment by oyai32** [comment]
theSidebar可以控制侧边栏，但是我这个框架里还没加动态路由，得你自己写了。等过几天我有空了才会加上。

**Comment by LYL98** [comment]
OK,还有就是el-select怎么改成hover触发显示子元素呢

**Comment by oyai32** [comment]
el-select用的是element的，没接触过hover触发，你可以自己找下
