### ISSUE TITLE
請問樣式表看起來會有重複的?

### ISSUE THREAD

**Issue by ultrarider821** [oyai32/vuebase#2]
請問樣式表看起來會重複很多次 這個是什麼原因造成的呢?

![00000](https://user-images.githubusercontent.com/7247267/64608207-bac1e780-d3fc-11e9-8cf4-c5069db7bf09.jpg)

**Comment by ultrarider821** [comment]
抱歉  我發現是因為開發環境才會這樣，正式佈上去就不會有這問題了:)

**Comment by oyai32** [comment]
因为我其实是先用了element的那套默认皮肤，然后再重写的样式，而且是直接重写了element-variables.scss，所以开发时看到很多样式被覆盖。但是打包的时候webpack其实会做处理，把重复的去掉，所以正式环境上看不到
